POC 1 added external conf

diff --git a/POC 1/cpu-monitoring b/POC 1/cpu-monitoring
--- a/POC 1/cpu-monitoring
+++ b/POC 1/cpu-monitoring
@@ -1,12 +1,18 @@
 #!/bin/bash
 
-# Configurable
+timeToSleep=1m
 blockLines=10
 
 counter=0
 
+function printHelp() {
+    echo "-t <sleep time>       Time to sleep between each iteration. Check man sleep for time format."
+    echo "-l <line number>      Lines printed in the log before a header printing"
+    echo "-h                    Print this helper message"
+}
+
 function logProcess() {
-    psOutput=$(ps -eo pid,ppid,%mem,%cpu,args --sort=-%cpu | head -n 2)
+    psOutput=$(ps -eo pid,ppid,%mem,%cpu,comm --sort=-%cpu | head -n 2)
     header="DATE $(echo "$psOutput" | sed -n 1p)"
     process="$(date +%m-%d-%Y+%T) $(echo "$psOutput" | sed -n 2p)"
     toPrint=$(echo -e "$header \n $process" | column -t)
@@ -18,6 +24,22 @@ function logProcess() {
         echo "$toPrint" | sed -n 2p
     fi
 }
+
+######################## OPTION PARSING ########################
+
+while getopts ":ht:l:" opt; do
+	case $opt in
+	    h) printHelp ;;
+        t) timeToSleep=${OPTARG} ;;
+        l) blockLines=${OPTARG} ;;
+	    \?) echo "Invalid option -${OPTARG}" ; exit 1;;
+	esac
+done
+shift $((OPTIND-1))
+
+
+
+######################## MAIN BODY ########################
 
 while true; do
     if [ $counter -eq 0 ]
@@ -32,5 +54,5 @@ while true; do
         fi
     fi
     counter=$[$counter+1]
-    sleep 1s
+    sleep $timeToSleep
 done
